#默认使用配置
spring:
  profiles:
    active: dev

---

#开发配置
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://130.211.63.202/db_dev?characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
#    type: com.alibaba.druid.pool.DruidDataSource